export const Questions4 = [
  {
    id: 49,
    que: "Rate your satisfaction with the choice of your career",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["thankfulness", "anger-management", "satisfaction"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 50,
    que: "Rate your satisfaction with your present job/business/school",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["satisfaction", "thankfulness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 51,
    que: "Rate your satisfaction with your capacity to have fun",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["exercise", "fitness", "physical-health"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 52,
    que: "Rate your satisfaction with the amount of fun experienced in last month ",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["thankfulness", "exercise", "fitness", "physical-health"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 53,
    que: "Rate your satisfaction with your financial prospects",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["thankfulness", "thanksgiving"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 54,
    que: "Rate your satisfaction with your current income level",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["satisfaction", "thankfulness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 55,
    que: "Rate your satisfaction with your level of self-esteem",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["self-love"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 56,
    que: "Rate your satisfaction with the prospects for having impact on those who know you and possibly others",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["thanksgiving", "thankfulness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 57,
    que: "Rate your satisfaction with your sex life",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["thankfulness", "confidence", "self-love"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 58,
    que: "Rate your satisfaction with your body, how it looks and performs",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["self-love"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 59,
    que: "Rate your satisfaction with your home life",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["self-love", "faith", "thanksgiving"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 60,
    que: "Rate your satisfaction with your life skills and knowledge of issues and facts unrelated to your job or profession",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["confidence", "peace", "stress"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 61,
    que: "Rate your satisfaction with your stress management capacities",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["stress", "anger-management"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 62,
    que: "Rate your satisfaction with your nutritional knowledge, attitudes, and choices ",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["physical-health", "healthy-diet", "nutrition"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 63,
    que: "Rate your satisfaction with your ability to recover from disappointment, hurts, setbacks, and tragedies",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["overthinking", "thankfulness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 64,
    que: "Rate your satisfaction with your confidence that you currently are, or will in the future be, reasonably close to your highest potential",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["faith", "social-anxiety"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 65,
    que: "Rate your satisfaction with your achievement of a rounded or balanced quality in your life",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["peace", "kindness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 66,
    que: "Rate your satisfaction with your sense that life for you is on an upward curve, getting better and fuller all the time",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["thankfulness", "overthinking"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 67,
    que: "Rate your satisfaction with your level of participation in issues and concerns beyond your immediate interests",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["kindness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 68,
    que: "Rate your satisfaction with your choice whether to parent or not and with the consequences or results of that choice",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["parenting"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 69,
    que: "Rate your satisfaction with your Emotional acceptance of the inescapable reality of aging",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["therapy"],
    gender: "neutral",
    agegroup: "all",
  },
];
