export const Questions1 = [
  {
    id: 1,
    que: "How often do you experience headaches?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
    keywords: ["stress", "depression", "anxiety"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 2,
    que: "How often do you experience tense muscles, sore back and neck?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
    keywords: ["physical-health", "stress", "depression", "anxiety"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 3,
    que: "How often do you experience fatigue?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
    keywords: ["exercise", "fitness", "physical-health"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 4,
    que: "How often do you experience anxiety, worry or phobias?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
    keywords: ["anxiety", "stress", "phobia"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 5,
    que: "How often do you experience difficulty falling asleep?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
    keywords: ["insomania", "stress", "depression"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 6,
    que: "How often do you experience irritability?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
    keywords: ["irritability", "anxiety", "anger-management"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 7,
    que: "How often do you experience insomnia?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
    keywords: ["insomania", "stress", "depression"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 8,
    que: "How often do you experience bouts of anger/hostility?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
    keywords: ["anger-management", "stress", "anxiety"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 9,
    que: "How often do you experience boredom or depression?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
    keywords: ["depression"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 10,
    que: "How often do you eat too much or too little?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
    keywords: ["physical-health", "healthy-diet", "nutrition"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 11,
    que: "How often do you experience diarrhea, cramps, gas or constipation?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
    keywords: ["physical-health", "healthy-diet", "nutrition"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 12,
    que: "How often do you experience restlessness, itching or tics?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
    keywords: ["stress", "anger-management", "irritability"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 13,
    que: "How frequently do you moderately exercise?",
    op1: "Daily",
    op2: "3-4 times per week",
    op3: "Once or twice a week",
    op4: "Once or twice a month",
    op5: "Seldom",
    keywords: ["exercise", "fitness", "physical-health"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 14,
    que: "How often do you get a full, restful night of sleep?",
    op1: "Almost every night",
    op2: "3-4 times per week",
    op3: "Once or twice a week",
    op4: "Once or twice a month",
    op5: "Seldom",
    keywords: ["insomania", "stress", "fitness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 15,
    que: "To what extent is your energy sufficient for your work and daily activities?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
    keywords: ["exercise", "fitness", "physical-health"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 16,
    que: "How closely does your weight approach the ideal level?",
    op1: "My weight is at the ideal level",
    op2: "My weight is almost close to the ideal level",
    op3: "My weight is close to the ideal level",
    op4: "My weight is not close to the ideal level",
    op5: "I am dangerously overweight/ underweight",
    keywords: ["exercise", "fitness", "physical-health"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 17,
    que: "To what extent do you eat a nutritious diet?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
    keywords: ["physical-health", "healthy-diet", "nutrition"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 18,
    que: "Which of the following best describes your use of tobacco?",
    op1: "In no period of my life have I had the habit of smoking or chewing tobacco",
    op2: "Early in my life for a short period I smoked or chewed tobacco",
    op3: "I stopped smoking or chewing tobacco over the past two years",
    op4: "I smoke or chew tobacco fairly often",
    op5: "I smoke or chew tobacco almost everyday",
    keywords: ["healthy-diet", "de-addiction", "rehab"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 19,
    que: "Which of the following best describes your use of alcohol?",
    op1: "I do not abuse alcohol, and never have",
    op2: "Very occasionally I abuse alcohol",
    op3: "I have a history of abusing alcohol, but am not presently abusing it",
    op4: "I abuse alcohol whenever I feel sad or depressed",
    op5: "I abuse alcohol almost daily",
    keywords: ["healthy-diet", "de-addiction", "rehab"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 70,
    que: "In the last week, how often have you been upset because of something that happened unexpectedly?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
    keywords: ["self-control", "self-management", "stress", "coping"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 71,
    que: "In the last week, how often have you felt that you were unable to control important things in your life?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
    keywords: ["self-control", "self-management", "coping"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 72,
    que: "In the last week, how often have you felt nervous and 'stressed'?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
    keywords: ["stress", "faith", "self-control", "coping"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 73,
    que: "In the last week, how often have you felt confident about your ability to handle your personal problems?",
    op1: "Very Often",
    op2: "Fairly Often",
    op3: "Sometimes",
    op4: "Almost Never",
    op5: "Never",
    keywords: ["faith", "self-control", "self-management", "coping"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 74,
    que: "In the last week, how often have you felt that things were going your way?",
    op1: "Very Often",
    op2: "Fairly Often",
    op3: "Sometimes",
    op4: "Almost Never",
    op5: "Never",
    keywords: ["faith", "self-management"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 75,
    que: "In the last week, how often have you found that you could NOT cope with all the things you had to do?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
    keywords: ["self-control", "coping", "faith"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 76,
    que: "In the last week, how often have you been able to control irritations in your life?",
    op1: "Very Often",
    op2: "Fairly Often",
    op3: "Sometimes",
    op4: "Almost Never",
    op5: "Never",
    keywords: ["self-control", "irritability"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 77,
    que: "In the last week, how often have you felt that you were on top of things?",
    op1: "Very Often",
    op2: "Fairly Often",
    op3: "Sometimes",
    op4: "Almost Never",
    op5: "Never",
    keywords: ["self-management", "self-control", "faith", "stress"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 78,
    que: "In the last week, how often have you been angered because of things that happened that were out of your control?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
    keywords: [
      "anger-management",
      "self-control",
      "self-management",
      "irritatability",
      "coping",
    ],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 79,
    que: "In the last week, how often have you felt difficulties were piling up so high that you could not overcome them?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
    keywords: ["coping", "stress", "faith"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 80,
    que: "How often do you feel lethargic or get tired more easily in the week leading up to your period in comaparison to the rest of your cycle?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
    keywords: ["menstrual-health", "menstrual-hygiene", "menstrual-problems"],
    gender: "female",
    agegroup: "adult",
  },
  {
    id: 81,
    que: "When you are due on your period, how likely are you to indulge in overeating or crave certain foods?",
    op1: "Very unlikely",
    op2: "Unlikely",
    op3: "Likely",
    op4: "Very likely",
    op5: "Most likely",
    keywords: ["menstrual-health", "menstrual-hygiene", "menstrual-problems"],
    gender: "female",
    agegroup: "adult",
  },
  {
    id: 82,
    que: "How often do you find yourself to be either excessively sleepy or unable to sleep during your period?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
    keywords: ["menstrual-health", "menstrual-hygiene", "menstrual-problems"],
    gender: "female",
    agegroup: "adult",
  },
  {
    id: 83,
    que: "In the week prior to menstruation, how often do you experience physical symptoms such as breast tenderness or swelling, joint or muscle pain, bloating, or weight gain?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
    keywords: ["menstrual-health", "menstrual-hygiene", "menstrual-problems"],
    gender: "female",
    agegroup: "adult",
  },
];
