export const Questions3 = [
  {
    id: 35,
    que: "What is your best guess as to the extent and quality of contact you had with your parent(s) shortly after birth?",
    op1: "Was given an above average amount of contact by happy parent",
    op2: "Was given an average amount of contact by happy parent",
    op3: "Was given an average amount of contact by unhappy (perhaps angry) parent(s)",
    op4: "Was given a below average amount of contact by unhappy (perhaps angry) parent(s)",
    op5: "Was given the least amount of contact by unhappy (perhaps angry) parent(s)",
    keywords: ["thankfulness", "thanksgiving", "kindness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 36,
    que: "During your early childhood, to what extent was your mother both calm and generally permissive?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
    keywords: ["anger-management", "anxiety", "kindness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 37,
    que: "How easily do you make friends in a strange situation?",
    op1: "Very easily",
    op2: "Fairly easily",
    op3: "Easily",
    op4: "Uneasily",
    op5: "Very uneasily",
    keywords: ["social-anxiety", "friendliness", "kindness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 38,
    que: "When highly stressed, how likely are you to ask friends or relatives for help? ",
    op1: "Most likely",
    op2: "Very likely",
    op3: "Likely",
    op4: "Unlikely",
    op5: "Very unlikely",
    keywords: ["social-anxiety", "friendliness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 39,
    que: "In comparison with other people, how likely are you to see others as threatening, uncooperative, or exploitative?",
    op1: "Highly unlikely",
    op2: "Very unlikely",
    op3: "Unlikely",
    op4: "Very likely",
    op5: "Highly likely",
    keywords: ["social-anxiety", "friendliness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 40,
    que: "How often are you confused about the intentions of others toward you?",
    op1: "Very infrequently",
    op2: "Infrequently",
    op3: "Frequently",
    op4: "Very frequently",
    op5: "Almost always",
    keywords: ["overthinking", "social-anxiety", "friendliness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 41,
    que: "Rate your satisfaction with your role in some kind of network of friends, relatives, and/or others about whom you care deeply and who reciprocate that commitment to you",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["social-anxiety", "friendliness"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 42,
    que: "Rate your satisfaction with your marital status",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["loyalty"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 43,
    que: "Rate your satisfaction with your primary relationships",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["thankfulness", "peace"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 44,
    que: "How often do you engage in a spiritual practice such as prayer, mediation, or inspirational reading to enrich your interior life?",
    op1: "Daily or more often",
    op2: "3-4 times per week",
    op3: "Once or twice a week",
    op4: "Once or twice a month",
    op5: "Seldom",
    keywords: ["spirituality", "prayer", "meditation"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 45,
    que: "How connected do you feel to your conception of a higher power or to a worthy cause?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
    keywords: ["spirituality", "thankfulness", "meditation"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 46,
    que: "To what extent do you believe your life has purpose?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
    keywords: ["spirituality", "thanksgiving", "meditation"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 47,
    que: "How much contact do you have with what you would consider a spiritual community?",
    op1: "Very much",
    op2: "Fairly much",
    op3: "Not very much",
    op4: "Little",
    op5: "Very little",
    keywords: ["spirituality", "thankfulness", "prayer"],
    gender: "neutral",
    agegroup: "all",
  },
  {
    id: 48,
    que: "Rate your satisfaction with your spirituality",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
    keywords: ["spirituality", "thankfulness", "meditation", "prayer"],
    gender: "neutral",
    agegroup: "all",
  },
];
