export const randomqueries = [
 'stress',
  'anxiety',
  'depression',
  'anger-management',
  'irritability',
  'phobia',
  'insomania',
  'exercise',
  'fitness',
  'physical-health',
  'healthy-diet',
  'nutrition',
  'de-addiction',
  'rehabilitation',
  'self-control',
  'self-management',
  'faith',
  'coping',
  'resilience',
  'yoga',
  'meditation',
  'decision-making',
  'leadership',
  'peace',
  'thankfulness',
  'thanksgiving',
  'kindness',
  'overthinking',
  'social-anxiety',
  'friendliness',
  'spirituality',
  'prayer',
  'menstrual-health',
  'menstrual-hygiene',
  'menstrual-problems',
  'loyalty',
  'satisfaction',
  'self-love' ,
  'confidence' ,
  'parenting' ,
  'therapy',
];
